apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.project }}
  namespace: {{ .Values.project }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.project }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.memory }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.hpa.memory }}
  {{- end }}
  {{- if .Values.hpa.cpu }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
